### ISSUE TITLE
[Feature Request] Use Miniart instead of Fanart for the Page

### ISSUE THREAD

**Issue by mattipunkt** [ABJC/ABJC-tvOS#16]
Because the titles are not shown, maybe you can use the Mini-Art from Jellyfin for the Pages.

**Comment by noahkamara** [comment]
Hey Matti,
could you explain what you mean by mini-art or Fanart?
Maybe this will help:

- Media Items currently use the "Backdrop" image for its 16/9 aspect ratio. 
- If you're items don't have a backdrop image with a title you can enable "Always show Titles" in preferences.
