### ISSUE TITLE
[Feature Request] Allow to choose from multiple Audiotracks

### ISSUE THREAD

**Issue by mattipunkt** [ABJC/ABJC-tvOS#18]
You can open the Options Menu, while playing, but there is only a „Unknown“ Audio.

**Comment by stephenb10** [comment]
To add to this, the [docs](https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/selecting_subtitles_and_alternative_audio_tracks) only explain how to retrieve information from the response and no way to add our own.

**Comment by noahkamara** [comment]
I agree with @stephenb10. To my knowledge this is not possible with the current implementation of VideoPlayer in SwiftUI. 
I created a feature request with Apple. Let's hope this will be included with the next version of SwiftUI
