### ISSUE TITLE
[ISSUE] Improve performance

### ISSUE THREAD

**Issue by mattipunkt** [ABJC/ABJC-tvOS#19]
The App is darn slow and, in cause of that, partly not functional.

**Comment by noahkamara** [comment]
Hey Matti,
you can try enabling "Fugly-Mode" in settings to improve performance as a quick fix (this will disable all images though).
Im still trying to find the reason for the animation hitches

**Comment by noahkamara** [comment]
I have traced the performance issues back to V- & H-Stacks. They just seem to perform very poorly on tvOS (the app performs fine on the budget iPad). I'm gonna look into implementing UICollectionView inside SwiftUI and compare performance.

**Comment by noahkamara** [comment]
Ok. Performance with UICollectionView is way better but implementation might be tricky (I'll have to embed SwiftUI inside UIKit inside SwiftUI 🤯) so it might take a while
