### ISSUE TITLE
[ENHANCEMENT] User select when opening app

### ISSUE THREAD

**Issue by N0Klu3** [ABJC/ABJC-tvOS#30]
**Is your feature request related to a problem? Please describe.**

I have multiple users so that the kids have a profile that’s unlocked and locked parents profile so that they don’t see the adult posters. 
Id really like it to prompt to sign into a user or at least be able to set a default user account. And then have a button at the top for account switching. 

**Describe the solution you'd like**

Best solution is to open app and then if you have users attached to your server to auto ask which user. Eg Netflix style or Emby style. 
There also needs to be a easy user switch option. 

**Describe alternatives you've considered**

Emby has this option and JF on Android I believe 

**Additional context**

Please I really need this to save my AppleTV and my WAF.

**Comment by stephenb10** [comment]
Looking to add this in #28
