### ISSUE TITLE
Alerts.auth.title

### ISSUE THREAD

**Issue by Headcold** [ABJC/ABJC-tvOS#34]
When I enter in my host address  "https://mydigitalchoice.net"  and username and password I get these series of errors on main page.

Alerts.auth.title
Alerts.auth.failed
Bottoms.ok. - is the name of the button on main screen

I am using latest version of tvOS 14.6 Appletv

Have not been able to login. Works on JellyFin so its not the credentials.

**Comment by Casao** [comment]
I had the same issue, while I was trying different things I submitted the first screen without a port number entered and the app crashed. 

After starting the app back up again, it connected fine on the first try.

**Comment by balajeek** [comment]
in my case i got the same error first, then clicked 'button' then entered ip,port manually followed by login, then i got the same alert error, now it won't open

**Comment by tidemann** [comment]
Tried build 27 now. Issue presist.
