### ISSUE TITLE
Crashes immediately

### ISSUE THREAD

**Issue by memnos** [ABJC/ABJC-tvOS#37]
**Describe the bug**
I installed build 26 from testflight and as soon as i  start ABJC it crashes without making anything
If i install build 25 all is fine, then reinstall built 26 and it crashes 
I cannot do anything.

**Comment by Brickme** [comment]
Same issue tvOS 14.7 l reverted back to TestFlight build (25)

**Comment by memnos** [comment]
I managed not to making crash only if i turn off jellyfin server.
So it is crashing only while connecting to server.

**Comment by danopat** [comment]
same issue apple tv 4k 2017 tvos 14.7

**Comment by noahkamara** [comment]
Hey there,
I'm working on the issue right now and I think I've found the culprit.
Please test the upcoming Build 27 and verify that the bug is resolved. If its not, please reopen this issue :D
