### ISSUE TITLE
[BUG] alerts.api.couldn't fetch itemslabel error

### ISSUE THREAD

**Issue by Fabeuss** [ABJC/ABJC-tvOS#42]
**Describe the bug**
Change some settings, like 'Always show titles' or other settings like order...

**To Reproduce**
1. Go to 'settings'
2. Click on 'Always show titles....or something else'
3. Click back to movies or tv shows
4. 'alerts.api.title'
5. 'alerts.api.Couldn't fetch Itemslabel'
6. 'buttons.ok'

**Expected behavior**
No error message...

**Device & Version:**
 - tvOS Version: [14.7]
 - ABJC Version [1.0.0]
 - ABJC Build [latest beta]

**Comment by noahkamara** [comment]
Hey Fabeuss,
does the issue persist after a restart of the app / Apple TV?

**Comment by Fabeuss** [comment]
Hi, yes I just restarted the atv and the error message reappeared almost instantly when going to the tv show tab...

**Comment by noahkamara** [comment]
Ok. Then the issue is probably within the preferences loading logic. I'll take a look and try to reproduce it. Thanks for your report
