### ISSUE TITLE
Search is broken when using voice dictation

### ISSUE THREAD

**Issue by mueslimak3r** [ABJC/ABJC-tvOS#46]
### Description of the Issue

Searching by entering letters using the on-screen keyboard works. But using voice dictation does nothing. There are no results or indication that typing a query performed a search.

### Steps to Reproduce

Search for media

### tvOS Version

Latest

### ABJC Version

Latest TestFlight

**Comment by noahkamara** [comment]
Hey,
I think I've found the issue and fixed it. It'll be in the next alpha build

**Comment by noahkamara** [comment]
The latest build resolves this issue. If you're still experiencing the bug, reopen the issue :)
