### ISSUE TITLE
playing a movie and then stopping it and trying to play a different movie will always load the first movie

### ISSUE THREAD

**Issue by mueslimak3r** [ABJC/ABJC-tvOS#47]
### Description of the Issue

if a movie is played and then stopped, playing a different movie will just play the first movie. Only restarting the app will allow a different movie to be played

### Steps to Reproduce

play a movie
stop that movie
try to play a different movie

### tvOS Version

latest

### ABJC Version

latest test flight

**Comment by noahkamara** [comment]
Hey there,
sorry for the late reply. 
Could you email me the mail-address you're using in TestFlight? I'd like to invite you to the alpha build that implements a TVVLCKit for video playback.

[noah@abjc.tech](mailto:noah@abjc.tech)

**Comment by mueslimak3r** [comment]
> Hey there,
> sorry for the late reply. 
> Could you email me the mail-address you're using in TestFlight? I'd like to invite you to the alpha build that implements a TVVLCKit for video playback.
> 
> [noah@abjc.tech](mailto:noah@abjc.tech)

Will do! I've never set up a debugger with an apple tv before so this'll be fun 🙂

**Comment by noahkamara** [comment]
The latest build resolves this issue, so I'm closing it. If you're still experiencing the issue, please reopen
