### ISSUE TITLE
Playback Failure with AVC1 and HVC1

### ISSUE THREAD

**Issue by G10vanni74** [ABJC/ABJC-tvOS#50]
### Description of the Issue

Hello Noah

I just noticed that some of my movies crash

I have movies in 4K HDR which pass and others not and the same for the H264.

I noticed one thing but I am not an expert, when the video is handled by the AVC1 and HVC1  codec, it crashes.

### tvOS Version

15

### ABJC Version

The last

**Comment by noahkamara** [comment]
Hi Giovanni,
thanks for the report. I'm aware of the issue and I'm working on a fix :)
